POST http://localhost:3000/userapi/signup
Content-Type: application/json

{
   
    "username":"pone",
    "email":"TELL@gmail.com",
    "password":"1234567",
    "confirmPassword":"1234567"
}

###
POST http://localhost:3000/userapi/login
Content-Type: application/json

{
    "email":"TELL@gmail.com",
    "password":"1234567"
}

###

POST http://localhost:3000/userapi/createPost
Content-Type: application/json

{
    "Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MDE2ZGRhODBkYzE0NDBjNGYyZmZkYiIsInVzZXJuYW1lIjoicG9uZSIsImVtYWlsIjoiVEVMTEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRLaDk3dDZuU09TMUlNUEs0VUp0NEZ1dkFpbnE0U3plNDU3dklMWld2UklwdGNTNmVIaUw3dSIsImRhdGUiOiIyMDIzLTAzLTAzVDAzOjQ3OjM4LjQyNVoiLCJfX3YiOjB9LCJpYXQiOjE2Nzc4NTA4MTksImV4cCI6MTY3Nzg1NDQxOX0.WfHcfZ-gcNE-aEan67EPGjWh61OHgqPmnQipQndw2nU"
}